### PR TITLE
Feature/test

### PR DESCRIPTION
**Pull request by widzthedvloper**
This branch contains all the unit tests for the two main functions :
the function that creates a project.
The function that creates a task.

Note: `npm run test`  to run the test suites.

### CODE REVIEW

**Review by e71az — CHANGES_REQUESTED** [review]
# Status:  Changes Required ♻️

Hello @widzthedvloper and @george-shammar,

Good job so far, all your tests are passing and you did a wide variety of them, however, there is a really specific thing that you need to do in this project, to test all your functions.

Right now you are only testing your taskCreation and projectCreation functions. Please add 2-3 test cases for each of the missing functions.

Please correct those issues and send another review request, good luck, and well done!

**Review by taiwo2 — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED ⚠️ 🚧 
Hey @widzthedvloper and @george-shammar, thanks for trying hard to implement what the previous Code Reviewer suggest, I must commend your  effort in adding `myTask function` however more function are still yet to be tested kindly test them.

**Comment by george-shammar** [comment]
The essential functions in the application have been covered by tests. The few untested functions are merely calling other functions that are already tested in another module.

**Review by afanimartin — APPROVED** [review]
## Approved ✅ ✅ ✅ 
Nice work making the requested changes. Merge and continue to the next project.

### Martin Afani
#### Slack: whiz25

**Pull request merged**
